on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
      - name: Get date
        id: date
        run: echo "::set-output name=date::$(date +%F)"

      - name: Cache
        uses: actions/cache@v1
        with:
          path: /var/cache/pacman/pkg
          key: arch-pkgs-${{ steps.date.outputs.date }}
          restore-keys: arch-pkgs

      - name: Update system and install dependencies
        run: pacman -Syu --noconfirm --noprogressbar --needed dbus python-jeepney python-pytest python-pytest-cov mypy flake8

      - name: Checkout
        uses: actions/checkout@v2

      - name: Static analysis with mypy
        run: mypy --ignore-missing-imports --strict -p dbus_objects

      - name: Lint with flake8
        run: flake8 . --count --show-source --statistics

      - name: Run tests
        run: |
          eval $(dbus-launch --sh-syntax)
          pytest -v --cov --cov-report=xml

      - name: Send coverage report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
